# Content for each proposal site. Every fact comes from public sources (see "sources");
# anything not found publicly (some prices, full menus) is left blank rather than invented.

def F(name, family, extra="wght@400;500;600;700"):
    return name, family, extra

DAY_CLOSED = []

SITES = [
# ---------------------------------------------------------------- Le Kechmarra
{
  "slug": "le-kechmarra", "name": "Le Kechmarra", "city_short": "Caen", "city": "14000 Caen",
  "address": "16 rue du Vaugueux", "tel": "09 81 41 80 88", "tel_intl": "+33981418088",
  "meta_desc": "Le Kechmarra, restaurant marocain et bar lounge au 16 rue du Vaugueux à Caen. Tajines, couscous et pâtisseries faits maison, halal.",
  "sources": "Petit Futé, Tripadvisor, page Wix du restaurant",
  "theme": {
    "fonts_href": "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;1,400;1,500&family=Jost:wght@400;500;600;700&display=swap",
    "serif": '"Cormorant Garamond", Georgia, serif', "sans": '"Jost", system-ui, sans-serif',
    "bg": "#0d1a1b", "bg_rgb": "13,26,27", "bg2": "#112224", "card": "#15292b",
    "line": "rgba(230,214,190,.11)", "text": "#f3e9da", "muted": "#a9b0a5", "soft": "#d9d2c3",
    "accent": "#c9663f", "accent2": "#e8946a", "on_accent": "#1a0b05",
    "gold": "#d4ac5e", "gold_soft": "rgba(212,172,94,.35)", "glow": "rgba(201,102,63,.24)", "ghost": "rgba(255,255,255,.28)",
    "pattern": "zellige", "pattern_color": "rgba(212,172,94,.17)",
  },
  "logo": "Le Kechmarra", "logo_sub": "CAEN",
  "hero_kicker": ("Restaurant marocain · Bar lounge", "Moroccan restaurant · Lounge bar"),
  "h1": ("Marrakech, <em>rue du Vaugueux.</em>", "Marrakech, <em>on rue du Vaugueux.</em>"),
  "lead": ("Tajines mijotés, couscous généreux et pâtisseries maison. Une cuisine marocaine préparée en famille, au cœur du Vaugueux.",
           "Slow-cooked tagines, generous couscous and homemade pastries. Moroccan cooking made by the family, in the heart of the Vaugueux."),
  "hero_meta": [(("Halal", "Halal"), ("Boucherie locale", "Local butcher")),
                (("Terrasse", "Terrace"), ("& bar lounge", "& lounge bar")),
                (("Vaugueux", "Vaugueux"), ("16 rue du Vaugueux", "16 rue du Vaugueux"))],
  "hero_icon": "tagine", "orbit": ["teapot", "couscous", "lantern"],
  "marquee": ["Tajine kefta", "Couscous", "Salade marocaine", "Thé à la menthe", "Pâtisseries maison", "Bricks", "Halal", "Terrasse"],
  "about_icon": "teapot",
  "badge": (("100 % maison", "100% homemade"), ("Plats et pâtisseries", "Dishes and pastries")),
  "about_h": ("Une affaire de famille, <em>une table marocaine.</em>", "A family affair, <em>a Moroccan table.</em>"),
  "about_p": [
    ("Kechmarra, c'est Marrakech en verlan. Ici, on travaille en famille et c'est la maman, Touria, qui tient la cuisine : tous les plats, comme toutes les pâtisseries, sont faits maison.",
     "Kechmarra is Marrakech spelled backwards in French slang. This is a family house, and mum Touria runs the kitchen: every dish and every pastry is made in-house."),
    ("La viande est halal et vient de bouchers locaux, pour une traçabilité complète. Le thé à la menthe se savoure en terrasse, dans l'une des plus jolies rues de Caen.",
     "The meat is halal and comes from local butchers, fully traceable. Mint tea is best enjoyed on the terrace, on one of the prettiest streets in Caen."),
  ],
  "pillars": [(("Fait maison", "Homemade"), ("Plats et pâtisseries", "Dishes and pastries")),
              (("Halal", "Halal"), ("Viande de bouchers locaux", "Meat from local butchers")),
              (("Événements", "Events"), ("Mariages, anniversaires", "Weddings, birthdays"))],
  "sig_h": ("Les <em>signatures</em> de Touria", "Touria's <em>signatures</em>"),
  "sig_p": ("Les recettes de la maison, mijotées comme au Maroc.", "House recipes, slow-cooked the Moroccan way."),
  "signatures": [
    {"icon": "tagine", "tag": ("Le classique", "The classic"), "name": ("Tajine kefta", "Kefta tagine"),
     "desc": ("Viande hachée, oignons, tomates et œufs.", "Minced meat, onions, tomatoes and eggs."), "price": "15,50 €"},
    {"icon": "couscous", "tag": ("Généreux", "Generous"), "name": ("Couscous", "Couscous"),
     "desc": ("Poulet, merguez et légumes.", "Chicken, merguez and vegetables."), "price": "17,80 €"},
    {"icon": "tagine", "tag": ("Sucré-salé", "Sweet & savoury"), "name": ("Tajine de veau", "Veal tagine"),
     "desc": ("Veau, pruneaux et amandes.", "Veal, prunes and almonds."), "price": "18,50 €"},
    {"icon": "teapot", "tag": ("Pour finir", "To finish"), "name": ("Thé à la menthe", "Mint tea"),
     "desc": ("Avec les pâtisseries de la maison.", "With the house pastries."), "price": ""},
  ],
  "menu_h": ("Mijoté avec patience, <em>servi avec le sourire.</em>", "Slow-cooked with patience, <em>served with a smile.</em>"),
  "menu": [
    {"label": ("Entrées", "Starters"), "kicker": ("Pour commencer", "To begin"), "icon": "salad", "items": [
      {"name": ("Salade marocaine", "Moroccan salad"), "desc": ("Salade fraîche à la marocaine", "Fresh Moroccan-style salad"), "price": "6,50 €", "icon": "salad"},
      {"name": ("Salade 2 bricks", "Salad & 2 briks"), "desc": ("Salade et deux bricks croustillantes", "Salad with two crispy briks"), "price": "7,60 €", "icon": "pastry"},
    ]},
    {"label": ("Tajines", "Tagines"), "kicker": ("Mijotés maison", "Slow-cooked in-house"), "icon": "tagine", "items": [
      {"name": ("Tajine kefta", "Kefta tagine"), "desc": ("Viande hachée, oignons, tomates, œufs", "Minced meat, onions, tomatoes, eggs"), "price": "15,50 €", "icon": "tagine"},
      {"name": ("Tajine poulet", "Chicken tagine"), "desc": ("Poulet, pommes de terre, citron et olives", "Chicken, potatoes, lemon and olives"), "price": "16,80 €", "icon": "tagine"},
      {"name": ("Tajine de veau", "Veal tagine"), "desc": ("Veau, pruneaux et amandes", "Veal, prunes and almonds"), "price": "18,50 €", "icon": "tagine"},
    ]},
    {"label": ("Couscous", "Couscous"), "kicker": ("Semoule fine", "Fine semolina"), "icon": "couscous", "items": [
      {"name": ("Couscous", "Couscous"), "desc": ("Poulet, merguez et légumes", "Chicken, merguez and vegetables"), "price": "17,80 €", "icon": "couscous"},
      {"name": ("Couscous légumes", "Vegetable couscous"), "desc": ("Couscous aux légumes · végétarien", "Vegetable couscous · vegetarian"), "price": "15,90 €", "icon": "leaf"},
    ]},
    {"label": ("Thé & douceurs", "Tea & sweets"), "kicker": ("Pour finir", "To finish"), "icon": "teapot", "items": [
      {"name": ("Thé à la menthe", "Mint tea"), "desc": ("Servi à la marocaine", "Served the Moroccan way"), "price": "", "icon": "tea"},
      {"name": ("Pâtisseries maison", "Homemade pastries"), "desc": ("Préparées sur place par la famille", "Made on site by the family"), "price": "", "icon": "baklava"},
    ]},
  ],
  "menu_note": ("Carte indicative établie à partir d'informations publiques : prix à confirmer sur place. Cuisine halal.",
                "Indicative menu based on public information: prices to be confirmed on site. Halal kitchen."),
  "schedule": [[[720, 870], [1140, 1440]], [[720, 870], [1140, 1440]], [], [], [[720, 870], [1140, 1440]], [[720, 870], [1140, 1440]], [[720, 870], [1140, 1440]]],
  "hours_h": ("Midi et soir, <em>jusqu'à minuit.</em>", "Lunch and dinner, <em>until midnight.</em>"),
  "payments": [("Carte bancaire", "Card"), ("Espèces", "Cash")],
  "services": [("Sur place", "Dine in"), ("À emporter", "Takeaway"), ("Terrasse", "Terrace"), ("Réservation", "Bookings"), ("Événements privés", "Private events"), ("Halal", "Halal")],
  "links": [{"href": "https://www.facebook.com/lekechmarra/", "label": "Facebook", "text": ("Suivez-nous", "Follow us")}],
  "cta_h": ("Une table en terrasse ? <em>Appelez-nous.</em>", "A table on the terrace? <em>Give us a call.</em>"),
  "cta_p": ("Réservations, groupes et événements privés : la famille vous répond.", "Bookings, groups and private events: the family will answer."),
},
# ---------------------------------------------------------------- Le Figuier
{
  "slug": "le-figuier", "name": "Le Figuier", "city_short": "Caen", "city": "14000 Caen",
  "address": "13-15 rue Saint-Michel", "tel": "02 31 78 81 32", "tel_intl": "+33231788132",
  "meta_desc": "Le Figuier, restaurant libanais familial au 13-15 rue Saint-Michel à Caen. Mezzés froids et chauds, grillades, pâtisseries, tout fait maison.",
  "sources": "Tendance Ouest, Tripadvisor, Sluurpy",
  "theme": {
    "fonts_href": "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;1,400;1,500&family=DM+Sans:wght@400;500;600;700&display=swap",
    "serif": '"Playfair Display", Georgia, serif', "sans": '"DM Sans", system-ui, sans-serif',
    "bg": "#17101a", "bg_rgb": "23,16,26", "bg2": "#1d1420", "card": "#241928",
    "line": "rgba(240,225,235,.10)", "text": "#f5ece6", "muted": "#b4a6ae", "soft": "#ddd0d4",
    "accent": "#a3bd8c", "accent2": "#c5d9b0", "on_accent": "#12160e",
    "gold": "#d2a866", "gold_soft": "rgba(210,168,102,.33)", "glow": "rgba(150,70,125,.32)", "ghost": "rgba(255,255,255,.28)",
    "pattern": "arches", "pattern_color": "rgba(210,168,102,.15)",
  },
  "logo": "Le Figuier", "logo_sub": "CAEN",
  "hero_kicker": ("Restaurant libanais · Rue Saint-Michel", "Lebanese restaurant · Rue Saint-Michel"),
  "h1": ("La table libanaise, <em>à partager.</em>", "Lebanese food, <em>made to share.</em>"),
  "lead": ("Mezzés froids et chauds, grillades et douceurs. Une cuisine de famille, faite maison, où l'on remplit la table de petits plats.",
           "Hot and cold mezze, grills and sweets. Homemade family cooking, where the table fills up with small dishes."),
  "hero_meta": [(("Depuis 2017", "Since 2017"), ("Famille Hachem", "The Hachem family")),
                (("Mezzés", "Mezze"), ("Froids & chauds", "Hot & cold")),
                (("Caen", "Caen"), ("13-15 rue Saint-Michel", "13-15 rue Saint-Michel"))],
  "hero_icon": "fig", "orbit": ["hummus", "skewer", "baklava"],
  "marquee": ["Houmous", "Taboulé", "Baba ghanouj", "Falafel", "Chich taouk", "Kafta", "Fattouch", "Baklava", "Vins libanais"],
  "about_icon": "hummus",
  "badge": (("Cuisine de partage", "Food for sharing"), ("Beaucoup de petits plats sur la table", "Lots of small dishes on the table")),
  "about_h": ("Une famille, <em>une cuisine de partage.</em>", "One family, <em>a cuisine for sharing.</em>"),
  "about_p": [
    ("Sami et Asmahan Hachem ont repris Le Figuier en 2017. Avec leur fille Clara, ils cuisinent le Liban de tradition : « une cuisine de partage, avec souvent beaucoup de petits plats sur la table ».",
     "Sami and Asmahan Hachem took over Le Figuier in 2017. With their daughter Clara, they cook traditional Lebanese food: “food for sharing, often with lots of small dishes on the table”."),
    ("Ici, tout est fait maison, sauf le baklava, qui demande un vrai savoir-faire. Les saveurs sont épicées sans être piquantes, et chacun trouve son assiette : végétarien, vegan ou sans allergènes.",
     "Everything is homemade, except the baklava, which takes real expertise. Flavours are spiced rather than spicy, and there's something for everyone: vegetarian, vegan or allergen-free."),
  ],
  "pillars": [(("Fait maison", "Homemade"), ("Mezzés et grillades", "Mezze and grills")),
              (("Pour tous", "For everyone"), ("Vegan, végétarien, sans allergènes", "Vegan, vegetarian, allergen-free")),
              (("Traiteur", "Catering"), ("Événements et privatisation", "Events and private hire"))],
  "sig_h": ("Les <em>signatures</em> de la maison", "House <em>signatures</em>"),
  "sig_p": ("Les classiques libanais, préparés comme en famille.", "Lebanese classics, made the family way."),
  "signatures": [
    {"icon": "skewer", "tag": ("Grillade", "From the grill"), "name": ("Kafta", "Kafta"),
     "desc": ("Viande hachée au persil et à l'oignon, houmous et fattouch.", "Minced meat with parsley and onion, hummus and fattoush."), "price": "16,50 €"},
    {"icon": "skewer", "tag": ("Le favori", "The favourite"), "name": ("Chich taouk", "Shish taouk"),
     "desc": ("Brochettes de poulet mariné, sauce à l'ail.", "Marinated chicken skewers, garlic sauce."), "price": ""},
    {"icon": "hummus", "tag": ("À partager", "To share"), "name": ("Plateau de mezzés", "Mezze platter"),
     "desc": ("Pour 2 à 4 personnes.", "For 2 to 4 people."), "price": "36 – 65 €"},
    {"icon": "baklava", "tag": ("Douceur", "Sweet"), "name": ("Baklava", "Baklava"),
     "desc": ("Feuilleté au beurre et aux fruits secs.", "Buttery layered pastry with nuts."), "price": ""},
  ],
  "menu_h": ("Remplissez la table, <em>on s'occupe du reste.</em>", "Fill the table, <em>we'll handle the rest.</em>"),
  "menu": [
    {"label": ("Mezzés froids", "Cold mezze"), "kicker": ("Pour commencer", "To begin"), "icon": "hummus", "items": [
      {"name": ("Houmous", "Hummus"), "desc": ("Pois chiches, tahiné, citron", "Chickpeas, tahini, lemon"), "price": "", "icon": "hummus"},
      {"name": ("Taboulé", "Tabbouleh"), "desc": ("Persil, tomate, boulgour, citron", "Parsley, tomato, bulgur, lemon"), "price": "", "icon": "salad"},
      {"name": ("Baba ghanouj", "Baba ghanoush"), "desc": ("Caviar d'aubergine", "Smoky aubergine dip"), "price": "", "icon": "bowl"},
      {"name": ("Fattouch", "Fattoush"), "desc": ("Salade croquante au pain grillé", "Crunchy salad with toasted bread"), "price": "", "icon": "salad"},
    ]},
    {"label": ("Mezzés chauds", "Hot mezze"), "kicker": ("Tout juste sortis", "Fresh from the kitchen"), "icon": "falafel", "items": [
      {"name": ("Falafels", "Falafel"), "desc": ("Pois chiches et herbes · végétarien", "Chickpeas and herbs · vegetarian"), "price": "", "icon": "falafel"},
      {"name": ("Kebbeh abou klil", "Kibbeh abou klil"), "desc": ("Boulgour, pomme de terre et feta · végétarien", "Bulgur, potato and feta · vegetarian"), "price": "", "icon": "leaf"},
    ]},
    {"label": ("Grillades", "Grills"), "kicker": ("Au charbon", "From the grill"), "icon": "skewer", "items": [
      {"name": ("Kafta", "Kafta"), "desc": ("Viande hachée, persil, oignon, avec houmous et fattouch", "Minced meat, parsley, onion, with hummus and fattoush"), "price": "16,50 €", "icon": "skewer"},
      {"name": ("Chich taouk", "Shish taouk"), "desc": ("Brochettes de poulet mariné, sauce à l'ail", "Marinated chicken skewers, garlic sauce"), "price": "", "icon": "skewer"},
    ]},
    {"label": ("À partager & desserts", "Sharing & desserts"), "kicker": ("Pour finir en beauté", "A sweet finish"), "icon": "baklava", "items": [
      {"name": ("Plateau de mezzés", "Mezze platter"), "desc": ("Pour 2 à 4 personnes", "For 2 to 4 people"), "price": "36 – 65 €", "icon": "hummus"},
      {"name": ("Baklava", "Baklava"), "desc": ("Feuilleté au beurre et aux fruits secs", "Buttery layered pastry with nuts"), "price": "", "icon": "baklava"},
      {"name": ("Crêpes à la crème de lait", "Milk-cream crêpes"), "desc": ("Dessert libanais traditionnel", "Traditional Lebanese dessert"), "price": "", "icon": "pastry"},
      {"name": ("Vins libanais", "Lebanese wines"), "desc": ("Une sélection du Liban", "A selection from Lebanon"), "price": "", "icon": "drink"},
    ]},
  ],
  "menu_note": ("Carte indicative établie à partir d'informations publiques : prix à confirmer sur place. Options vegan, végétariennes et sans allergènes.",
                "Indicative menu based on public information: prices to be confirmed on site. Vegan, vegetarian and allergen-free options."),
  "schedule": [[[720, 840], [1140, 1320]]] * 6 + [[]],
  "hours_h": ("Midi et soir, <em>du lundi au samedi.</em>", "Lunch and dinner, <em>Monday to Saturday.</em>"),
  "payments": [("Carte bancaire", "Card"), ("Espèces", "Cash")],
  "services": [("Sur place", "Dine in"), ("À emporter", "Takeaway"), ("Livraison", "Delivery"), ("Terrasse", "Terrace"), ("Accès PMR", "Wheelchair access"), ("Traiteur", "Catering")],
  "links": [{"href": "mailto:contact.lefiguier@gmail.com", "label": "E-mail", "text": ("contact.lefiguier@gmail.com", "contact.lefiguier@gmail.com")},
            {"href": "https://www.facebook.com/lefiguiercaen/", "label": "Facebook", "text": ("Suivez-nous", "Follow us")}],
  "cta_h": ("Un repas en famille ? <em>On dresse la table.</em>", "A family meal? <em>We'll set the table.</em>"),
  "cta_p": ("Réservez par téléphone, ou commandez à emporter.", "Book by phone, or order to take away."),
},
# ---------------------------------------------------------------- L'Oriental Couscous
{
  "slug": "oriental-couscous", "name": "L'Oriental Couscous", "city_short": "Caen", "city": "14000 Caen",
  "address": "6 quai Amiral Hamelin", "tel": "02 31 34 35 36", "tel_intl": "+33231343536",
  "meta_desc": "L'Oriental Couscous, cuisine algérienne familiale au 6 quai Amiral Hamelin à Caen. Couscous maison, menus à partager, à emporter et en livraison.",
  "sources": "site du restaurant, Petit Futé",
  "theme": {
    "fonts_href": "https://fonts.googleapis.com/css2?family=Marcellus&family=Karla:wght@400;500;600;700&display=swap",
    "serif": '"Marcellus", Georgia, serif', "sans": '"Karla", system-ui, sans-serif',
    "bg": "#0e1220", "bg_rgb": "14,18,32", "bg2": "#121729", "card": "#171d33",
    "line": "rgba(220,225,245,.10)", "text": "#f2eee6", "muted": "#a3a8bd", "soft": "#d6d6e0",
    "accent": "#e3a33a", "accent2": "#f2c06a", "on_accent": "#1a1004",
    "gold": "#d9b46a", "gold_soft": "rgba(217,180,106,.33)", "glow": "rgba(79,179,169,.22)", "ghost": "rgba(255,255,255,.28)",
    "pattern": "lattice", "pattern_color": "rgba(217,180,106,.14)",
  },
  "logo": "L'Oriental Couscous", "logo_sub": "CAEN",
  "hero_kicker": ("Cuisine algérienne · Quai Amiral Hamelin", "Algerian cuisine · Quai Amiral Hamelin"),
  "h1": ("Le couscous <em>de famille.</em>", "Family-style <em>couscous.</em>"),
  "lead": ("Semoule roulée à la main, épices parfumées, recettes transmises de génération en génération. Sur place, à emporter ou livré chez vous.",
           "Hand-rolled semolina, fragrant spices, recipes passed down through generations. Dine in, take away or have it delivered."),
  "hero_meta": [(("Fait maison", "Homemade"), ("Recettes ancestrales", "Heirloom recipes")),
                (("Livraison", "Delivery"), ("Dès 30 € de commande", "From a €30 order")),
                (("Caen", "Caen"), ("6 quai Amiral Hamelin", "6 quai Amiral Hamelin"))],
  "hero_icon": "couscous", "orbit": ["teapot", "baklava", "star"],
  "marquee": ["Couscous royal", "Couscous oriental", "Couscous bédouin", "Couscous végétarien", "Kemia", "Samoussas", "Baklawa", "Makrout", "Thé à la menthe"],
  "about_icon": "star",
  "badge": (("Semoule roulée main", "Hand-rolled semolina"), ("Comme à la maison", "Just like at home")),
  "about_h": ("Une histoire de famille, <em>transmise à table.</em>", "A family story, <em>passed on at the table.</em>"),
  "about_p": [
    ("L'Oriental Couscous, c'est avant tout une histoire familiale : une cuisine algérienne traditionnelle, transmise de génération en génération, avec des produits locaux, une semoule roulée à la main et des épices parfumées.",
     "L'Oriental Couscous is first of all a family story: traditional Algerian cooking passed down through generations, with local produce, hand-rolled semolina and fragrant spices."),
    ("En cuisine, Vincent a été formé pendant sept ans par Malika Kouba à ses recettes. David Nabet, à la tête de la maison, en perpétue l'héritage, avec Elena en second.",
     "In the kitchen, Vincent spent seven years learning Malika Kouba's recipes. David Nabet, who runs the house, carries on the legacy, with Elena as sous-chef."),
  ],
  "pillars": [(("Fait maison", "Homemade"), ("Recettes ancestrales", "Heirloom recipes")),
              (("À emporter", "Takeaway"), ("Et en livraison", "And delivery")),
              (("À partager", "To share"), ("Menus 2 et 4 personnes", "Menus for 2 and 4"))],
  "sig_h": ("Les <em>signatures</em> de la maison", "House <em>signatures</em>"),
  "sig_p": ("Le couscous sous toutes ses formes, et de quoi partager.", "Couscous in every style, and plenty to share."),
  "signatures": [
    {"icon": "couscous", "tag": ("Le plus complet", "The works"), "name": ("Couscous oriental", "Oriental couscous"),
     "desc": ("La grande assiette de la maison.", "The house's grandest plate."), "price": "23,90 €"},
    {"icon": "leaf", "tag": ("Végétarien", "Vegetarian"), "name": ("Couscous végétarien", "Vegetarian couscous"),
     "desc": ("Légumes et semoule roulée main.", "Vegetables and hand-rolled semolina."), "price": "11,50 €"},
    {"icon": "lantern", "tag": ("Pour deux", "For two"), "name": ("Menu Touareg", "Touareg menu"),
     "desc": ("Le menu à partager pour 2 personnes.", "The sharing menu for 2 people."), "price": "38,90 €"},
    {"icon": "baklava", "tag": ("Douceur", "Sweet"), "name": ("Pâtisseries orientales", "Oriental pastries"),
     "desc": ("Baklawa, samsa ou makrout.", "Baklawa, samsa or makrout."), "price": "3,50 €"},
  ],
  "menu_h": ("La semoule est roulée, <em>la table est mise.</em>", "The semolina is rolled, <em>the table is set.</em>"),
  "menu": [
    {"label": ("Couscous", "Couscous"), "kicker": ("Le cœur de la maison", "The heart of the house"), "icon": "couscous", "items": [
      {"name": ("Couscous végétarien", "Vegetarian couscous"), "desc": ("Légumes · végétarien", "Vegetables · vegetarian"), "price": "11,50 €", "icon": "leaf"},
      {"name": ("Couscous poulet", "Chicken couscous"), "desc": ("Poulet et légumes", "Chicken and vegetables"), "price": "", "icon": "couscous"},
      {"name": ("Couscous bédouin", "Bedouin couscous"), "desc": ("Spécialité de la maison", "House speciality"), "price": "", "icon": "couscous"},
      {"name": ("Couscous royal", "Royal couscous"), "desc": ("Le grand classique", "The great classic"), "price": "", "icon": "couscous"},
      {"name": ("Couscous oriental", "Oriental couscous"), "desc": ("La grande assiette de la maison", "The house's grandest plate"), "price": "23,90 €", "icon": "couscous"},
    ]},
    {"label": ("Menus", "Menus"), "kicker": ("À partager", "To share"), "icon": "lantern", "items": [
      {"name": ("Menu Touareg", "Touareg menu"), "desc": ("Pour 2 personnes", "For 2 people"), "price": "38,90 €", "icon": "lantern"},
      {"name": ("Menu Médina", "Medina menu"), "desc": ("Pour 4 personnes", "For 4 people"), "price": "76,90 €", "icon": "star"},
      {"name": ("Menu étudiant", "Student menu"), "desc": ("Sur présentation de la carte étudiant", "With a student card"), "price": "12,90 €", "icon": "couscous"},
    ]},
    {"label": ("Entrées & bowls", "Starters & bowls"), "kicker": ("Pour commencer", "To begin"), "icon": "bowl", "items": [
      {"name": ("Kemia", "Kemia"), "desc": ("Petites entrées à picorer", "Small bites to nibble"), "price": "2,00 €", "icon": "salad"},
      {"name": ("Samoussas", "Samosas"), "desc": ("Croustillants et parfumés", "Crispy and fragrant"), "price": "6,00 €", "icon": "pastry"},
      {"name": ("Poké bowls", "Poke bowls"), "desc": ("Plusieurs recettes", "Several recipes"), "price": "11,50 – 15,90 €", "icon": "bowl"},
    ]},
    {"label": ("Desserts & thé", "Desserts & tea"), "kicker": ("Pour finir", "To finish"), "icon": "teapot", "items": [
      {"name": ("Baklawa", "Baklawa"), "desc": ("Feuilleté aux fruits secs et au miel", "Nut and honey pastry"), "price": "3,50 €", "icon": "baklava"},
      {"name": ("Samsa", "Samsa"), "desc": ("Triangle aux amandes", "Almond pastry triangle"), "price": "3,50 €", "icon": "pastry"},
      {"name": ("Makrout", "Makrout"), "desc": ("Semoule et dattes", "Semolina and dates"), "price": "3,50 €", "icon": "pastry"},
      {"name": ("Thé à la menthe", "Mint tea"), "desc": ("Servi chaud", "Served hot"), "price": "", "icon": "tea"},
    ]},
  ],
  "menu_note": ("Prix à emporter, d'après la carte publiée par le restaurant. Livraison : +2 € par plat, dès 30 € de commande. À confirmer avec la maison.",
                "Takeaway prices, from the menu published by the restaurant. Delivery: +€2 per dish, from a €30 order. To be confirmed with the restaurant."),
  "schedule": [[], [], [[660, 840], [1020, 1320]], [[660, 840], [1020, 1320]], [[660, 840], [1020, 1320]], [[660, 840], [1020, 1320]], [[690, 840], [1080, 1290]]],
  "hours_h": ("Du mercredi <em>au dimanche.</em>", "Wednesday <em>to Sunday.</em>"),
  "payments": [("Carte bancaire", "Card"), ("Espèces", "Cash")],
  "services": [("Sur place", "Dine in"), ("À emporter", "Takeaway"), ("Livraison", "Delivery"), ("Uber Eats", "Uber Eats"), ("Deliveroo", "Deliveroo"), ("Événements", "Events")],
  "links": [{"href": "https://www.instagram.com/lorientalcouscous_caen/", "label": "Instagram", "text": ("Suivez-nous", "Follow us")},
            {"href": "https://www.facebook.com/orientalcouscouscaen/", "label": "Facebook", "text": ("Rejoignez-nous", "Join us")}],
  "cta_h": ("Un couscous ce soir ? <em>Appelez, on le prépare.</em>", "Couscous tonight? <em>Call and we'll make it.</em>"),
  "cta_p": ("Sur place, à emporter ou livré chez vous.", "Dine in, take away or delivered to your door."),
},
# ---------------------------------------------------------------- Babek
{
  "slug": "babek", "name": "Babek", "city_short": "Caen", "city": "14000 Caen",
  "address": "19 rue Écuyère", "tel": "02 31 50 87 26", "tel_intl": "+33231508726",
  "meta_desc": "Babek, le kebab réinventé au 19 rue Écuyère à Caen. Poulet français rôti à la broche, légumes de saison, sauces maison, pain au levain.",
  "sources": "Tendance Ouest, Uber Eats, Mister J",
  "theme": {
    "fonts_href": "https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter:wght@400;500;600;700&display=swap",
    "serif": '"Instrument Serif", Georgia, serif', "sans": '"Inter", system-ui, sans-serif',
    "bg": "#f4ede2", "bg_rgb": "244,237,226", "bg2": "#ece3d4", "card": "#fbf7f0",
    "line": "rgba(40,30,20,.13)", "text": "#1d1813", "muted": "#6b6156", "soft": "#3d352d",
    "accent": "#d6452c", "accent2": "#b93a22", "on_accent": "#fff8f0",
    "gold": "#a8772a", "gold_soft": "rgba(168,119,42,.35)", "glow": "rgba(214,69,44,.13)", "ghost": "rgba(29,24,19,.25)",
    "pattern": "dots", "pattern_color": "rgba(29,24,19,.13)", "scheme": "light",
  },
  "logo": "Babek", "logo_sub": "CAEN",
  "hero_kicker": ("Le kebab à l'envers · Rue Écuyère", "Kebab, flipped · Rue Écuyère"),
  "h1": ("Le kebab, <em>réinventé.</em>", "Kebab, <em>reinvented.</em>"),
  "lead": ("Poulet français mariné aux épices et rôti à la broche, légumes de saison, sauces maison et pain au levain de la boulangerie voisine.",
           "French chicken marinated in spices and spit-roasted, seasonal vegetables, house sauces and sourdough from the bakery next door."),
  "hero_meta": [(("Poulet français", "French chicken"), ("Rôti à la broche", "Spit-roasted")),
                (("De saison", "Seasonal"), ("Légumes du moment", "Vegetables of the moment")),
                (("Depuis 2021", "Since 2021"), ("19 rue Écuyère", "19 rue Écuyère"))],
  "hero_icon": "doner", "orbit": ["leaf", "bowl", "cheese"],
  "marquee": ["Babek", "Halloumi", "Bolbek bowl", "Falafel", "Houmous", "Frites au zaatar", "Pain au levain", "Légumes de saison"],
  "about_icon": "wrap",
  "badge": (("Babek = kebab", "Babek = kebab"), ("…écrit à l'envers", "…spelled backwards")),
  "about_h": ("Berlin dans le pain, <em>Caen dans l'assiette.</em>", "Berlin in the bread, <em>Caen on the plate.</em>"),
  "about_p": [
    ("Babek, c'est le mot kebab à l'envers. Étienne Godet a ouvert la maison en février 2021, inspiré par la culture kebab de Berlin, après être passé par les cuisines de Stéphane Carbone et d'Anthony Caillot.",
     "Babek is kebab spelled backwards. Étienne Godet opened it in February 2021, inspired by Berlin's kebab culture, after cooking in the kitchens of Stéphane Carbone and Anthony Caillot."),
    ("L'idée : tout faire maison, des marinades aux sauces, avec des légumes qui changent au fil des saisons et le pain de la boulangerie d'à côté. Un kebab de qualité, frais et léger.",
     "The idea: make everything in-house, from marinades to sauces, with vegetables that change with the seasons and bread from the bakery next door. A quality kebab, fresh and light."),
  ],
  "pillars": [(("Fait maison", "Homemade"), ("Marinades et sauces", "Marinades and sauces")),
              (("De saison", "Seasonal"), ("Légumes du moment", "Vegetables of the moment")),
              (("Végétarien", "Vegetarian"), ("Halloumi & falafel", "Halloumi & falafel"))],
  "sig_h": ("Les <em>signatures</em> de la maison", "House <em>signatures</em>"),
  "sig_p": ("Le kebab comme on ne l'a jamais goûté à Caen.", "Kebab like Caen has never tasted it."),
  "signatures": [
    {"icon": "wrap", "tag": ("L'original", "The original"), "name": ("Le Babek", "The Babek"),
     "desc": ("Pain au levain, volaille marinée aux épices, légumes de saison, feta, herbes fraîches.", "Sourdough, spiced chicken, seasonal vegetables, feta, fresh herbs."), "price": "13,50 €"},
    {"icon": "cheese", "tag": ("Végétarien", "Vegetarian"), "name": ("Halloumi Lover", "Halloumi Lover"),
     "desc": ("Le sandwich au halloumi grillé.", "The grilled halloumi sandwich."), "price": "14,50 €"},
    {"icon": "bowl", "tag": ("Sans pain", "No bread"), "name": ("Bolbek", "Bolbek"),
     "desc": ("Boulgour, houmous, volaille marinée, légumes de saison.", "Bulgur, hummus, marinated chicken, seasonal vegetables."), "price": "15,50 €"},
    {"icon": "fries", "tag": ("À côté", "On the side"), "name": ("Frites au zaatar", "Zaatar fries"),
     "desc": ("Croustillantes, relevées au zaatar.", "Crispy, with a zaatar kick."), "price": "4,00 €"},
  ],
  "menu_h": ("Simple, frais, <em>fait ici.</em>", "Simple, fresh, <em>made here.</em>"),
  "menu": [
    {"label": ("Sandwichs", "Sandwiches"), "kicker": ("Pain au levain", "Sourdough bread"), "icon": "wrap", "items": [
      {"name": ("Le Babek", "The Babek"), "desc": ("Volaille marinée, légumes de saison, feta, herbes, sauce maison", "Marinated chicken, seasonal vegetables, feta, herbs, house sauce"), "price": "13,50 €", "icon": "wrap"},
      {"name": ("Halloumi Lover", "Halloumi Lover"), "desc": ("Halloumi grillé · végétarien", "Grilled halloumi · vegetarian"), "price": "14,50 €", "icon": "cheese"},
      {"name": ("Grilled cheese", "Grilled cheese"), "desc": ("Le croque fondant de la maison", "The house's melty toastie"), "price": "7,50 €", "icon": "sandwich"},
    ]},
    {"label": ("Bowls", "Bowls"), "kicker": ("Sans pain", "No bread"), "icon": "bowl", "items": [
      {"name": ("Bolbek", "Bolbek"), "desc": ("Boulgour, houmous, volaille marinée, légumes de saison", "Bulgur, hummus, marinated chicken, seasonal vegetables"), "price": "15,50 €", "icon": "bowl"},
      {"name": ("Falafel bowl", "Falafel bowl"), "desc": ("Falafels et légumes de saison · végétarien", "Falafel and seasonal vegetables · vegetarian"), "price": "15,50 €", "icon": "falafel"},
    ]},
    {"label": ("À côté & desserts", "Sides & desserts"), "kicker": ("Pour compléter", "To go with it"), "icon": "fries", "items": [
      {"name": ("Frites au zaatar", "Zaatar fries"), "desc": ("Croustillantes, relevées au zaatar", "Crispy, with zaatar"), "price": "4,00 €", "icon": "fries"},
      {"name": ("Houmous & pita", "Hummus & pita"), "desc": ("Houmous maison", "Homemade hummus"), "price": "6,00 €", "icon": "hummus"},
      {"name": ("Fried chicken", "Fried chicken"), "desc": ("Poulet croustillant", "Crispy chicken"), "price": "9,00 €", "icon": "chicken"},
      {"name": ("Babettes", "Babettes"), "desc": ("Pommes dauphines façon churros", "Churro-style potato puffs"), "price": "", "icon": "pastry"},
      {"name": ("Mousse au chocolat", "Chocolate mousse"), "desc": ("Praliné noisette et sarrasin", "Hazelnut and buckwheat praline"), "price": "", "icon": "bowl"},
    ]},
  ],
  "menu_note": ("Prix relevés sur la carte en ligne, à confirmer sur place. Les légumes changent avec les saisons.",
                "Prices taken from the online menu, to be confirmed on site. Vegetables change with the seasons."),
  "schedule": [[], [[705, 855], [1140, 1335]], [[705, 855], [1140, 1335]], [[705, 855], [1140, 1335]], [[705, 855], [1140, 1335]], [[705, 855], [1140, 1335]], [[1140, 1335]]],
  "hours_h": ("Midi et soir, <em>six jours sur sept.</em>", "Lunch and dinner, <em>six days a week.</em>"),
  "payments": [("Carte bancaire", "Card"), ("Espèces", "Cash")],
  "services": [("Sur place", "Dine in"), ("À emporter", "Takeaway"), ("Terrasse", "Terrace"), ("Végétarien", "Vegetarian")],
  "links": [],
  "cta_h": ("Un Babek ce midi ? <em>Appelez, c'est prêt.</em>", "A Babek for lunch? <em>Call ahead, it's ready.</em>"),
  "cta_p": ("Commandez par téléphone et passez le récupérer.", "Order by phone and pick it up."),
},
# ---------------------------------------------------------------- Le Safran
{
  "slug": "le-safran", "name": "Le Safran", "city_short": "Caen", "city": "14000 Caen",
  "address": "11 rue Saint-Sauveur", "tel": "02 31 38 72 27", "tel_intl": "+33231387227",
  "meta_desc": "Le Safran, kebab familial au 11 rue Saint-Sauveur à Caen depuis 25 ans. Élu meilleur kebab de France en 2013, 2014 et 2018. Poulet mariné, sauce blanche maison.",
  "sources": "Tendance Ouest, Petit Futé, Tripadvisor",
  "theme": {
    "fonts_href": "https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Outfit:wght@400;500;600;700&display=swap",
    "serif": '"DM Serif Display", Georgia, serif', "sans": '"Outfit", system-ui, sans-serif',
    "bg": "#120c08", "bg_rgb": "18,12,8", "bg2": "#1a120c", "card": "#211710",
    "line": "rgba(255,230,200,.10)", "text": "#f6ecdf", "muted": "#b5a592", "soft": "#dccdb8",
    "accent": "#f0a71b", "accent2": "#f7c35a", "on_accent": "#1d1102",
    "gold": "#e0a43a", "gold_soft": "rgba(240,167,27,.30)", "glow": "rgba(200,60,40,.25)", "ghost": "rgba(255,255,255,.28)",
    "pattern": "quatrefoil", "pattern_color": "rgba(240,167,27,.13)",
  },
  "logo": "Le Safran", "logo_sub": "CAEN",
  "hero_kicker": ("Kebab de famille · Rue Saint-Sauveur", "Family kebab house · Rue Saint-Sauveur"),
  "h1": ("Le kebab <em>primé de Caen.</em>", "Caen's <em>award-winning kebab.</em>"),
  "lead": ("Filets de poulet marinés à l'huile d'olive, au citron et aux ingrédients secrets de la maison. Sauce blanche maison, pain frais, frites croustillantes.",
           "Chicken fillets marinated in olive oil, lemon and a few house secrets. Homemade white sauce, fresh bread, crispy fries."),
  "hero_meta": [(("3 ×", "3 ×"), ("Meilleur kebab de France", "Best kebab in France")),
                (("25 ans", "25 years"), ("Une affaire de famille", "A family business")),
                (("Caen", "Caen"), ("11 rue Saint-Sauveur", "11 rue Saint-Sauveur"))],
  "hero_icon": "doner", "orbit": ["crocus", "fries", "chicken"],
  "marquee": ["Kebab poulet", "Sauce blanche maison", "Frites croustillantes", "Pain frais", "Citron & huile d'olive", "Depuis 25 ans", "Petit Futé 2024"],
  "about_icon": "crocus",
  "badge": (("2013 · 2014 · 2018", "2013 · 2014 · 2018"), ("Élu meilleur kebab de France", "Voted best kebab in France")),
  "about_h": ("Ahmad, Keyvan et Marlène, <em>une histoire de famille.</em>", "Ahmad, Keyvan and Marlène, <em>a family story.</em>"),
  "about_p": [
    ("Depuis 25 ans, Le Safran régale la rue Saint-Sauveur. Chaque jour, Ahmad prépare lui-même la viande, épaulé par son fils Keyvan et sa femme Marlène.",
     "For 25 years, Le Safran has been feeding rue Saint-Sauveur. Every day Ahmad prepares the meat himself, helped by his son Keyvan and his wife Marlène."),
    ("Le secret : des filets de poulet 100 % marinés à l'huile d'olive, au citron et à quelques ingrédients bien gardés. Le résultat a été élu meilleur kebab de France en 2013, 2014 et 2018, et récompensé par le Petit Futé en 2024.",
     "The secret: 100% chicken fillets marinated in olive oil, lemon and a few closely kept ingredients. It was voted best kebab in France in 2013, 2014 and 2018, and won a Petit Futé award in 2024."),
  ],
  "pillars": [(("Viande du jour", "Meat of the day"), ("Préparée par Ahmad", "Prepared by Ahmad")),
              (("Sauce maison", "House sauce"), ("La fameuse sauce blanche", "The famous white sauce")),
              (("Traiteur", "Catering"), ("Pour vos événements", "For your events"))],
  "sig_h": ("Ce qui a fait <em>la réputation</em> du Safran", "What made Le Safran <em>famous</em>"),
  "sig_p": ("Peu de choses à la carte, mais chacune faite avec soin.", "A short menu, every item made with care."),
  "signatures": [
    {"icon": "doner", "tag": ("Le primé", "Award-winner"), "name": ("Kebab poulet", "Chicken kebab"),
     "desc": ("Filets de poulet marinés, pain frais, crudités.", "Marinated chicken fillets, fresh bread, salad."), "price": ""},
    {"icon": "hummus", "tag": ("Maison", "Homemade"), "name": ("Sauce blanche", "White sauce"),
     "desc": ("La recette de la maison, celle dont tout le monde parle.", "The house recipe everyone talks about."), "price": ""},
    {"icon": "fries", "tag": ("Croustillantes", "Crispy"), "name": ("Frites", "Fries"),
     "desc": ("Dorées et croustillantes, saluées par les habitués.", "Golden and crisp, a favourite with regulars."), "price": ""},
    {"icon": "sandwich", "tag": ("Le bon plan", "Good deal"), "name": ("Le menu", "The meal deal"),
     "desc": ("Le menu kebab de la maison.", "The house kebab meal."), "price": "9,50 €"},
  ],
  "menu_h": ("Une carte courte, <em>une recette parfaite.</em>", "A short menu, <em>a perfect recipe.</em>"),
  "menu": [
    {"label": ("Kebabs", "Kebabs"), "kicker": ("La spécialité", "The speciality"), "icon": "doner", "items": [
      {"name": ("Kebab poulet", "Chicken kebab"), "desc": ("Filets marinés à l'huile d'olive et au citron, pain frais, crudités, sauce blanche maison", "Fillets marinated in olive oil and lemon, fresh bread, salad, homemade white sauce"), "price": "", "icon": "doner"},
      {"name": ("Menu kebab", "Kebab meal"), "desc": ("Le menu de la maison", "The house meal deal"), "price": "9,50 €", "icon": "sandwich"},
    ]},
    {"label": ("À côté", "Sides"), "kicker": ("Pour compléter", "To go with it"), "icon": "fries", "items": [
      {"name": ("Frites", "Fries"), "desc": ("Croustillantes", "Crispy"), "price": "", "icon": "fries"},
      {"name": ("Boissons", "Drinks"), "desc": ("Sodas et eaux", "Sodas and water"), "price": "", "icon": "drink"},
    ]},
  ],
  "menu_note": ("Carte indicative établie à partir d'informations publiques : carte complète et prix à finaliser avec la maison. Paiement en espèces.",
                "Indicative menu based on public information: full menu and prices to be finalised with the restaurant. Cash payment."),
  "schedule": [[], [], [[720, 900], [1080, 1260]], [[720, 900], [1080, 1260]], [[720, 900], [1080, 1260]], [[720, 990], [1080, 1260]], []],
  "hours_h": ("Midi et soir, <em>du mercredi au samedi.</em>", "Lunch and dinner, <em>Wednesday to Saturday.</em>"),
  "payments": [("Espèces uniquement", "Cash only")],
  "services": [("Sur place", "Dine in"), ("À emporter", "Takeaway"), ("Traiteur", "Catering")],
  "links": [{"href": "https://www.facebook.com/kebablesafran", "label": "Facebook", "text": ("Suivez-nous", "Follow us")}],
  "cta_h": ("Vous passez ce midi ? <em>Appelez avant, c'est prêt.</em>", "Coming by at lunch? <em>Call ahead, it's ready.</em>"),
  "cta_p": ("Le midi, il y a du monde : commandez par téléphone pour éviter l'attente.", "Lunchtime gets busy: order by phone and skip the queue."),
},
]
